[tool.poetry]
name = "snakeml"
version = "0.1.0"
description = ""
authors = ["StarrFox <starrfox6312@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
tensorflow = "^2.11.1"
torch = "^1.13.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
