[package]
name = "compression_speed_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd = "0.12.4"
snap = "1.1.0"
lz4 = "1.23.1"