build:
    nim cpp --app:lib --threads:on -d:release --mm:arc --passC:-Ilib/libimhex/include/ \
    --passC:-std=c++20 --passC:-Ilib/external/nativefiledialog/src/include imhex_plugin_test.nim

install: build
    cp libimhex_plugin_test.so ~/.local/share/imhex/plugins/libimhex_plugin_test.hexplug

imhex: install
    imhex

test:
    nim cpp --threads:on --mm:arc --passC:-Ilib/libimhex/include/ \
    --passC:-std=c++20 --passC:-Ilib/external/nativefiledialog/src/include --run test.nim

clean:
    rm libimhex_plugin_test.so
    rm test
