benchmark: build
    hyperfine .build/fibnim ./build/fibc ./build/fibclang ./build/fibzig ./build/fibrust ./build/fibgo .build/fibcpp .build/fibcodon

build:
    mkdir build || true

    # c
    gcc -O3 -march=native -o build/fibc main.c

    # c with clang
    clang -O3 -march=native -o build/fibclang main.c

    # zig
    zig build-exe -O ReleaseFast main.zig
    mv main build/fibzig

    # rust
    rustc -C opt-level=3 -C panic=abort -C target-cpu=native main.rs
    mv main build/fibrust

    # go
    go build main.go
    mv main build/fibgo

    # cpp
    gcc -O3 -march=native -o build/fibcpp main.cpp

    # codon
    codon build --release -o build/fibcodon main.py

    # nim
    nim c --cc:gcc -d:danger --mm:arc --passC:-march=native --out:build/fibnim main.nim

clean:
    rm -rf build
    rm -rf zig-cache
