[tool.poetry]
name = "uname"
version = "0.1.0"
description = ""
authors = ["StarrFox <starrfox6312@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "unnamed_programming_lang"}]

[tool.poetry.dependencies]
python = "^3.10"
lark = "^1.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
