[package]
name = "llvm_testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.2"
inkwell = { version = "0.1.1", features = ["llvm14-0"] }

